version: '3.8'
services:
  webjack:
    image: nginx:alpine
    container_name: webjack
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./main.js:/usr/share/nginx/html/main.js:ro
      - ./cards:/usr/share/nginx/html/cards:ro
    restart: unless-stopped
